server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/shopdb
    username: shop
    password: shop123
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}

services:
  cart-url: ${CART_SERVICE_URL:http://cart-service:8085}