server:
  port: 8084

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres:5432/shopdb
    username: shop
    password: shop123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "MyVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm!!"
