server:
  port: 8086

spring:
  application:
    name: wishlist-service
  datasource:
    url: jdbc:postgresql://postgres:5432/shopdb
    username: shop
    password: shop123
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
