server:
  port: 8085

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://postgres:5432/shopdb
    username: shop
    password: shop123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    table: flyway_schema_history_cart
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

services:
  product-url: ${PRODUCT_SERVICE_URL:http://product-service:8084}
